# Generated by Django 3.1.2 on 2020-11-05 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_auto_20201031_1733'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('by', 'on')},
        ),
    ]
