# Generated by Django 3.1.2 on 2020-11-12 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0007_auto_20201112_1804'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers_count',
        ),
        migrations.RemoveField(
            model_name='user',
            name='following_count',
        ),
    ]
