# Generated by Django 3.1.2 on 2020-11-13 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_auto_20201112_1856'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='connection',
            unique_together={('user', 'follows')},
        ),
    ]
